name: Run Tests
on: [push]
env:
  AWS_REGION: us-east-1 # set this to your preferred AWS region, e.g. us-west-1
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download s3 file
        run: |
          aws s3 cp s3://otls-environment-files/.env.local .

      - name: Install modules
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.REGISTRY_TOKEN }}" >> ~/.npmrc
          echo "//npm.fontawesome.com/:_authToken=${{ secrets.FONTAWESOME_TOKEN }}" >> ~/.npmrc
          npm ci
      - name: Generate Prisma client
        run: npx prisma generate
      - name: Run tests
        run: npm run test:ci
      - name: Run typecheck`
        run: npm run typecheck
      - name: Run build
        run: npm run build
