# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main
  - devops-nvm-authentication

pool:
  vmImage: windows-latest

variables:
  NEXT_PUBLIC_AUTH0_ISSUER: https://dev-5h48g-bs.us.auth0.com
  DATABASE_HOST: otls-web-db-listener.comwo5tjfulx.us-east-1.rds.amazonaws.com
  DATABASE_NAME: OTLS-QA
  DATABASE_PORT: 1433
  TRUST_SERVER_CERTIFICATE: true
  NEXTAUTH_URL: https://qa.outreachtls.com

steps:
  - script: |
      echo //npm.pkg.github.com/:_authToken=%REGISTRY_TOKEN_EV% >> .npmrc
      call scripts\setup_env.cmd
    displayName: Set up .npmrc and .env.local with environment variables
    env:
      REGISTRY_TOKEN_EV: $(REGISTRY_TOKEN)
      NEXT_PUBLIC_AUTH0_CLIENT_ID: $(AUTH0_CLIENT_ID)
      AUTH0_CLIENT_SECRET: $(AUTH0_CLIENT_SECRET)
      DATABASE_USERNAME: $(DATABASE_USERNAME)
      DATABASE_PASSWORD: $(DATABASE_PASSWORD)
      NEXTAUTH_SECRET: $(NEXTAUTH_SECRET)
  - script: |
      call npm install
      call npm run build
    displayName: "npm install and build"

  - task: CopyFiles@2
    inputs:
      contents: |
        _types/**/*
        .next/**/*
        components/**/*
        database/**/*
        pages/**/*
        public/**/*
        scripts/**/*
        styles/**/*
        .env.local
        .npmrc
        web.config
        *.js
        *.ts
        *.json
        *.yml
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: OTLS"
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "next-otls"
    condition: succeeded()
