import { Organization } from "models/organization/organization.interface";

export interface SEOProps {
  seo_title?: string | null;
  seo_description?: string | null;
  social_image?: any;
}

export const US_STATES_AND_CANADIAN_TERRITORIES = [
  "AL",
  "AK",
  "AZ",
  "AR",
  "CA",
  "CO",
  "CT",
  "DC",
  "DE",
  "FL",
  "GA",
  "HI",
  "ID",
  "IL",
  "IN",
  "IA",
  "KS",
  "KY",
  "LA",
  "ME",
  "MD",
  "MA",
  "MI",
  "MN",
  "MS",
  "MO",
  "MT",
  "NE",
  "NV",
  "NH",
  "NJ",
  "NM",
  "NY",
  "NC",
  "ND",
  "OH",
  "OK",
  "OR",
  "PA",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VT",
  "VA",
  "WA",
  "WV",
  "WI",
  "WY",

  "AB",
  "BC",
  "LB",
  "MB",
  "NB",
  "NF",
  "NS",
  "NU",
  "NW",
  "ON",
  "PE",
  "QC",
  "SK",
  "YU",
];
export const dumbData: Organization[] = [
  {
    date_added: "Dec 10, 2021",
    organization: "IL School District 87",
    type: "School",
    main_contact: "Professor Geller	",
    location: "IL",
    members: 13,
    renewal_date: "Jan 01, 2023",
    created_by: "Org - IL Dept of Education",
    name: "Brooklyn PD",
    email: "rholt@b99.com",
    phone: "(123) 456-7890",
    address: {
      street: "Brooklyn",
      region: "NY",
      zip: "12345",
      value: "1 Police Ave",
    },
  },
  {
    date_added: "Dec 10, 2021",
    organization: "IL School District 87",
    type: "Police Department",
    main_contact: "Professor Geller	",
    location: "Brooklyn, NY",
    members: 13,
    renewal_date: "Jan 01, 2023",
    created_by: "Partner-Joe Smith",
    name: "Brooklyn PD",
    email: "rholt@b99.com",
    phone: "(123) 456-7890",
    address: {
      street: "Brooklyn",
      region: "NY",
      zip: "12345",
      value: "1 Police Ave",
    },
  },
  {
    date_added: "Dec 10, 2021",
    organization: "IL School District 87",
    type: "School",
    main_contact: "Professor Geller	",
    location: "IL",
    members: 13,
    renewal_date: "Jan 01, 2023",
    created_by: "Org - IL Dept of Education",
    name: "Brooklyn PD",
    email: "rholt@b99.com",
    phone: "(123) 456-7890",
    address: {
      street: "Brooklyn",
      region: "NY",
      zip: "12345",
      value: "1 Police Ave",
    },
  },
  {
    date_added: "Dec 10, 2021",
    organization: "IL School District 87",
    type: "School",
    main_contact: "Professor Geller	",
    location: "IL",
    members: 13,
    renewal_date: "Jan 01, 2023",
    created_by: "Org - IL Dept of Education",
    name: "Brooklyn PD",
    email: "rholt@b99.com",
    phone: "(123) 456-7890",
    address: {
      street: "Brooklyn",
      region: "NY",
      zip: "12345",
      value: "1 Police Ave",
    },
  },
  {
    date_added: "Dec 10, 2021",
    organization: "IL School District 87",
    type: "School",
    main_contact: "Professor Geller	",
    location: "IL",
    members: 13,
    renewal_date: "Jan 01, 2023",
    created_by: "Org - IL Dept of Education",
    name: "Brooklyn PD",
    email: "rholt@b99.com",
    phone: "(123) 456-7890",
    address: {
      street: "Brooklyn",
      region: "NY",
      zip: "12345",
      value: "1 Police Ave",
    },
  },
];
